### ISSUE TITLE
use of aws keys

### ISSUE THREAD

**Issue by silarsis** [SumoLogic/sumologic-kinesis-connector#12]
Heya,

Is there any reason the aws keys are required? If the AWS server is configured with an IAM role that provides appropriate access, should we be able to run without an access key and secret?

(I've tried to do this, but it complains that the key isn't set. I'm hoping the answer is "sure, we can remove the requirement for a key and let it fall back to the IAM role for the instance", because I'd rather not have to create a new user with access keys just to run this...)

Thanks :)

**Comment by cpliakas** [comment]
+1 for this feature request. We use IAM roles exclusively, it would be great to have this feature in the connector.

**Comment by statik** [comment]
This is important for us also. Will you accept pull requests to make the access key optional? Using hard coded keys this way conflicts with AWS best practice.

**Comment by duchatran** [comment]
@truppert-mdsol Would you like to submit a PR for this?

**Comment by truppert-mdsol** [comment]
@duchatran Absolutely!  I'll open individual PRs for each feature we merged into our fork.  Great to have it managed in the parent repo instead :)

**Comment by duchatran** [comment]
Thanks everyone, I merged the PRs, so closing this.
