### ISSUE TITLE
[question] Multiple kinesis streams?

### ISSUE THREAD

**Issue by baversjo** [SumoLogic/sumologic-kinesis-connector#13]
Is it possible for the connector to read multiple kinesis streams and forward them to different sumologic http endpoints?
The usecase is that I have one stream per each of my apps.

I was thinking as a workaround, I could launch multiple connectors on the same server?

**Comment by baversjo** [comment]
I have a working implementation for handling this, see #14

**Comment by duchatran** [comment]
Close since PR was merge
