### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by truppert-mdsol** [SumoLogic/sumologic-kinesis-connector#17]
Is this still the best way to ship logs from Kinesis to Sumologic?  

If not, could you please point me to the better way?

If so, are you open to PRs to bring things up to date and/or address issues reported in the repo?

**Comment by duchatran** [comment]
We do monitor this. Are you collecting your own logs via Kinesis or from other AWS services?

**Comment by truppert-mdsol** [comment]
We are deciding the best way to collect a significant flow of logs.  Kinesis is attractive because it has such high throughput capabilities.  Sumologic links to this repo for shipping logs from Kinesis.

With the most recent commits being ~3 years ago, I just wanted to confirm that this is still the best solution before putting work into setting it up.

**Comment by truppert-mdsol** [comment]
@duchatran I've opened a PR that corrects the Ant dependencies so that the app will start up using the commands in the README.  I am working to address a couple other issues reported in the repo that I also find necessary, but don't want to flood the repo with PRs all at once.  

If you have time, I would greatly appreciate a review/merging of the PR.

**Comment by duchatran** [comment]
Done, thanks for contributing @truppert-mdsol. Feel free to submit PR to update README as well. Closing this issue for now.
