### ISSUE TITLE
Long delay for connector to pull data out of Kinesis

### ISSUE THREAD

**Issue by duchatran** [SumoLogic/sumologic-kinesis-connector#9]
The connector seems to send data to Sumo roughly every 40 minutes. I was able to confirm this through both the connector output logs to the CLI, and the data sent to Sumo. 
A couple of things that make me think the issue could be with the connector code: 
1> I also run into cases at INITIAL  setup, where connector worker thread keeps sleeping, however there was data ready in the Kinesis stream as I could pull them out with the AWS CLI. 
2> AWS itself sends CWL every 10minutes. 

Below is some output logs: 
# 

02 Oct 2015 03:11:57,567  INFO Worker:529 - Current stream shard assignments: shardId-000000000000
02 Oct 2015 03:11:57,570  INFO Worker:529 - Sleeping ...
02 Oct 2015 03:12:58,581  INFO Worker:529 - Current stream shard assignments: shardId-000000000000
........< more sleeping, cut for brevity > ..
02 Oct 2015 03:27:12,757  INFO Worker:529 - Sleeping ...
02 Oct 2015 03:28:13,771  INFO Worker:529 - Current stream shard assignments: shardId-000000000000
02 Oct 2015 03:28:13,771  INFO Worker:529 - Sleeping ...
02 Oct 2015 03:28:23,165  INFO SumologicEmitter:56 - Sending batch of: 20 records
02 Oct 2015 03:28:24,794  INFO SequenceNumberValidator:80 - Validated sequence number 49554978305395257392612504814171510445454958370704326658 with shard id shardId-000000000000
02 Oct 2015 03:29:14,783  INFO Worker:529 - Current stream shard assignments: shardId-000000000000
02 Oct 2015 03:29:14,783  INFO Worker:529 - Sleeping ...
02 Oct 2015 03:30:15,797  INFO Worker:529 - Current stream shard assignments: shardId-000000000000
....<more sleeping, cut for brevity >........
02 Oct 2015 03:35:20,864  INFO Worker:529 - Sleeping ...
02 Oct 2015 03:36:21,874  INFO Worker:529 - Current stream shard assignments: shardId-000000000000
02 Oct 2015 03:36:21,874  INFO Worker:529 - Sleeping ...
02 Oct 2015 03:37:22,886  INFO Worker:529 - Current stream shard assignments: shardId-000000000000
02 Oct 2015 03:37:22,886  INFO Worker:529 - Sleeping ...
02 Oct 2015 03:38:23,897  INFO Worker:529 - Current stream shard assignments: shardId-000000000000
02 Oct 2015 03:38:23,897  INFO Worker:529 - Sleeping ...
02 Oct 2015 03:39:24,908  INFO Worker:529 - Current stream shard assignments: shardId-000000000000
02 Oct 2015 03:39:24,908  INFO Worker:529 - Sleeping ...
02 Oct 2015 03:40:25,920  INFO Worker:529 - Current stream shard assignments: shardId-000000000000
02 Oct 2015 03:40:25,921  INFO Worker:529 - Sleeping ...
02 Oct 2015 03:41:26,932  INFO Worker:529 - Current stream shard assignments: shardId-000000000000
....< more sleeping, cut for brevity>
02 Oct 2015 04:02:48,193  INFO Worker:529 - Current stream shard assignments: shardId-000000000000
02 Oct 2015 04:02:48,193  INFO Worker:529 - Sleeping ...
02 Oct 2015 04:03:49,205  INFO Worker:529 - Current stream shard assignments: shardId-000000000000
02 Oct 2015 04:03:49,206  INFO Worker:529 - Sleeping ...
02 Oct 2015 04:04:50,221  INFO Worker:529 - Current stream shard assignments: shardId-000000000000
02 Oct 2015 04:04:50,221  INFO Worker:529 - Sleeping ...
02 Oct 2015 04:05:51,231  INFO Worker:529 - Current stream shard assignments: shardId-000000000000
02 Oct 2015 04:05:51,231  INFO Worker:529 - Sleeping ...
02 Oct 2015 04:06:52,241  INFO Worker:529 - Current stream shard assignments: shardId-000000000000
02 Oct 2015 04:06:52,241  INFO Worker:529 - Sleeping ...
02 Oct 2015 04:07:53,251  INFO Worker:529 - Current stream shard assignments: shardId-000000000000
02 Oct 2015 04:07:53,251  INFO Worker:529 - Sleeping ...
02 Oct 2015 04:08:20,606  INFO SumologicEmitter:56 - Sending batch of: 20 records
02 Oct 2015 04:08:22,456  INFO SequenceNumberValidator:80 - Validated sequence number 49554978305395257392612504814195688961847415812223139842 with shard id shardId-000000000000
02 Oct 2015 04:08:54,263  INFO Worker:529 - Current stream shard assignments: shardId-000000000000

**Comment by duchatran** [comment]
Checked-in a fix.

**Comment by illeg** [comment]
i am facing the same issue.How do u fixed the problem?
